### ISSUE TITLE
[BUG] Placed foliage disappearing on scene reload as well as after starting/playing scene

### ISSUE THREAD

**Issue by DevLewa** [dreadpon/godot_spatial_gardener#37]
**Godot version**
"4.2.1"

**Plugin version**
"1.3.1 (stable) as well as current master branch"

**Platform**
"Windows 10"

**Issue description**
Meshes which are placed with the painting tool in a scene disappear if we play the scene via the "play scene" option in the editor.
In addition to that, saving and reloading the project also gets rid of the meshes. (Sometimes empty MultiMeshInstance nodes get left over in the gardener.)
I was also able to reproduce the same bug by switching between larger scenes (only happening in a larger project, I presume due to Godot loading/unloading scenes dynamically to avoid high memory usage?)

**Steps to Reproduce**
1.) Download attached "FoliageTest.zip" and extract. (uses current addon from master branch)
2.) open test.tscn, click on "Hardener" and select "Greenhouse_Plant_State"
3.) Start painting on the plane. Green blocks should appear.
![green](https://github.com/dreadpon/godot_spatial_gardener/assets/26333153/f2976733-e609-4b06-b2ac-d9fa7e9e3abd)

4.) save the scene with CTRL+S and start playing the scene. The cubes aren't visible:
![render](https://github.com/dreadpon/godot_spatial_gardener/assets/26333153/4ec74765-cc3c-439b-9c26-c7ad607d65af)

5.) closing and reopening the project also causes the cubes to disappear/not render properly.

**Minimal reproduction project**
[FoliageTest.zip](https://github.com/dreadpon/godot_spatial_gardener/files/13990454/FoliageTest.zip)

Apologies in advance if i'm missing crucial info here and/or if i'm not using the tool properly.
I saw this bugreport: https://github.com/dreadpon/godot_spatial_gardener/issues/36
Although in my case it doesn't have to do with the LOD distance. (I'ts by default on -1.)

I'll dig through the code to see what could be causing this but just in case i wanted to post this bugreport here.
In any case thank you for this great tool. :)

**/EDIT:**
Just found out that this bug happens if you use "SpawnedNode3D" instead of "Mesh" in the LOD settings. With regular meshes (.tres) files it works fine.

**Comment by dreadpon** [comment]
Fixed by https://github.com/dreadpon/godot_spatial_gardener/commit/4b045a1e2507b56454d0026d5a4b2f97bfc59ace

The issue was caused by a fix aimed at avoiding Vulkan buffer issues with `MultiMesh` resources (https://github.com/godotengine/godot/issues/68592) which set `MultiMesh` of an `OctreeNode` to `null` whenever it was outside the kill threshold.

Fixed by not doing that anymore and opt to just nulling the `MultiMesh.mesh` itself.

The Vulkan issue above was also also fixed, as there was an orphan `Node` which kept reference to `OctreeManager` resources and by extension `MultiMesh`. It didn't need to be a `Node`, so it was changed to `RefCounted`.
