### ISSUE TITLE
[BUG] Godot 3.5 rc4 - signal already exists in parent class

### ISSUE THREAD

**Issue by mchauta** [dreadpon/godot_spatial_gardener#8]
Hi, I don't know if this is a 3.5 thing only or not, but when I try to activate I can't becuase of a compile error. I tracked it down to the file:res://addons/dreadpon.spatial_gardener/controls/extensions/ui_signaling_hslider.gd
The error is "The signal 'drag_started' already exists in a parent class'.  Commenting out the signal declaration allows the plugin to compile and enable in the editor. Haven't yet tested the plugin further, but at least it enables now.

**Comment by dreadpon** [comment]
So I dug a bit.

Problem is caused by the update made in 3.5 where the (obviously) missing signals `drag_started` and `drag_ended` were added to the Slider class. My class ui_signaling_hslider.gd exists for the sole purpose of remedying that problem in 3.4.

There's also also a note to myself that this functionality is coming in 3.5 lol.

Commenting out `drag_started` seems to be the correct way to bypass this for now. My implementation of the opposite is named `drag_stopped`, so here there's no collision with the native signal.

Will get on it in the future.

**Comment by dreadpon** [comment]
There is a number of things I'd like to implement, including fixing this and making a proper 3.5 release.
I'll get to it soon.
