### ISSUE TITLE
add modifyable text labels to brushes

### ISSUE THREAD

**Issue by justinbarrett** [dreadpon/godot_spatial_gardener#9]
issue:
sometimes godot doesn't properly save a thumbnail to a scene or mesh resulting in a blank brush with a default text that does not reflect the instance stored in the brush. This leaves you guessing what the brush is.

This leads to a lot of trial and error when you have a diverse amount of fawna and clutter.

![gardener_labels_example2](https://user-images.githubusercontent.com/27959760/177163122-8582355f-1311-4454-8cf3-601a34aed7a7.png)

proposal:
I would like see see user editable labels on brushes...readable simply on the thumbnail or mouse over popup. 
 This would remove the trial and error method of figuring out what brush is what.

Aternative:
allow the user to supply their own thumbnail.

**Comment by dreadpon** [comment]
It makes sense to me to have 2 types of these labels: one for plant itself (the upper box) and one for resources referenced in `Lod Variants` and `Mesh`/`Spawned Spatial`.

Difference being that plant label should be a user-editable name, and resource label should contain a filename assigned.

There's 2 ways I see this going: 
- Keep the current layout and add a small header on top with a label (fig. 2)
- Replace the square shape with a rectangle, ordering plants in a vertical list instead of a grid (fig. 3 and fig. 4)

![thumbnail_rework](https://user-images.githubusercontent.com/35217125/177283642-4d794b62-28a5-4cc1-830e-a6261e8d9a84.png)

**Comment by justinbarrett** [comment]
I think fig 2 with the editable label on top...ordering plants in a grid allows more to be seen with less need for scrolling. Just my thoughts.

**Comment by dreadpon** [comment]
Thanks, I will take that into consideration.

**Comment by dreadpon** [comment]
@justinbarrett 
Done, currently only on my local machine.
Will publish together with the whole 1.1.0 update

![ui rework](https://user-images.githubusercontent.com/35217125/184532368-5587332a-73a1-4f8c-8e28-eb2d633f5938.png)
